name: "Terraform Deploy"
description: "Deploy Terraform configuration in a given directory using env-specific backend and tfvars"

inputs:
  env:
    description: "The Terraform environment (used to pick env/backend files)"
    required: true
    type: string
  directory:
    description: "The Terraform configuration directory"
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.9.8

    - name: Initialize Terraform
      working-directory: ${{ inputs.directory }}
      run: |
        terraform init \
          -backend-config="./environment-config/${{ inputs.env }}/${{ inputs.env }}.tfbackend" \
          -var-file="./environment-config/${{ inputs.env }}/${{ inputs.env }}.tfvars"
      shell: bash

    - name: Terraform Apply
      working-directory: ${{ inputs.directory }}
      run: |
        terraform apply -auto-approve -var-file="./environment-config/${{ inputs.env }}/${{ inputs.env }}.tfvars"
      shell: bash
