name: "Run Python Tests"
description: "Runs unittest tests in the 'test/' directory"

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: bash

    - name: Run tests
      run: |
        export PYTHONPATH="$PYTHONPATH:$(pwd)/src"
        python -m unittest discover -s "test"
      shell: bash
