name: Hello Matrix

on:
  push:
    branches:
      - develop

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        letter: [A, B, C]
    steps:
      - uses: actions/checkout@v4
      - name: Call hello action
        uses: ./.github/actions/terraform_deploy
        with:
          env: ${{ matrix.letter }}
          directory: "Directory"
