name: Hello Matrix

on:
  push:
    branches:
      - develop

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Python tests
        uses: ./.github/actions/run-tests


  set-terraform-env:
    runs-on: ubuntu-latest
    needs: run-tests
    outputs:
      terraform-env-list: ${{ steps.set-env.outputs.terraform-env-list }}
    steps:
      - name: Determine Terraform environment
        id: set-env
        run: |
          if [ "${GITHUB_REF_NAME}" == "develop" ]; then
            echo 'terraform-env-list=["dev"]' >> $GITHUB_OUTPUT
          elif [ "${GITHUB_REF_NAME}" == "staging" ]; then
            echo 'terraform-env-list=["staging"]' >> $GITHUB_OUTPUT
          elif [ "${GITHUB_REF_NAME}" == "master" ]; then
            echo 'terraform-env-list=["prod"]' >> $GITHUB_OUTPUT
          else
            echo 'terraform-env-list=[]' >> $GITHUB_OUTPUT
          fi

  terraform-deploy:
    runs-on: ubuntu-latest
    needs: set-terraform-env
    strategy:
      matrix:
        env: ${{ fromJSON(needs.set-terraform-env.outputs.terraform-env-list) }}
    steps:
      - uses: actions/checkout@v4
      - name: Call hello action
        uses: ./.github/actions/terraform_deploy
        with:
          env: ${{ matrix.env }}
          directory: "Directory"
