name: Lint and Test

on:
  pull_request:
    branches:
      - develop
      - staging
      - main

jobs:
  lint-and-test:
    environment: AWS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run linting
        run: |
          # Example: use flake8 as linter
          pip install flake8
          flake8 ./src

      - name: Confi gure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}


      - name: Run unit tests
        run: |
          export PYTHONPATH=./src:$PYTHONPATH
          python -m unittest discover -s "test"
